export const mockTasks = [
    {
        Id: 1,
        Title: "Develop Screens for OMT Mobile App",
        FeedBack: null,
        Comments: null,
        TotalTime: 7.25,
        PriorityRank: 4.6,
        LocalPriority: 1,
        WorkingAction: null,
        Remark: null,
        EstimatedTimeDescription: "7.25 h",
        TaskID: "T33790",
        Priority: "High",
        Status: 10,
        ItemRank: 1,
        IsTodaysTask: true,
        Body: null,
        PercentComplete: 70,
        Categories: null,
        StartDate: "2024-01-15",
        DueDate: null,
        Created: "2024-01-10",
        Modified: "2024-01-20",
        TaskLevel: 1,
        workingThisWeek: true,
        EstimatedTime: 7.25,
        Project: {
            Id: 257,
            Title: "OMT Mobile Application",
            PortfolioStructureID: "P257",
            PriorityRank: 1
        },
        ParentTask: null,
        Editor: { Id: 1, Title: "John Doe" },
        Portfolio: { Id: 1, Title: "Mobile Apps", PortfolioStructureID: "PF001" },
        TaskType: { Id: 1, Title: "Development", Level: 1 },
        Author: { Id: 1, Title: "John Doe" },
        AssignedTo: [{ Id: 1, Title: "John Doe" }],
        ResponsibleTeam: { Id: 1, Title: "Mobile Team" },
        TaskCategories: [{ Id: 1, Title: "Mobile" }]
    },
    {
        Id: 2,
        Title: "Replace Old Time Entry Popup with New Time Entry Popup in User Time Entry",
        FeedBack: null,
        Comments: null,
        TotalTime: 6.75,
        PriorityRank: 4.6,
        LocalPriority: 2,
        WorkingAction: null,
        Remark: null,
        EstimatedTimeDescription: "6.75 h",
        TaskID: "T33783",
        Priority: "High",
        Status: 10,
        ItemRank: 2,
        IsTodaysTask: true,
        Body: null,
        PercentComplete: 75,
        Categories: null,
        StartDate: "2024-01-14",
        DueDate: null,
        Created: "2024-01-09",
        Modified: "2024-01-19",
        TaskLevel: 1,
        workingThisWeek: true,
        EstimatedTime: 6.75,
        Project: {
            Id: 30,
            Title: "Timesheet Module",
            PortfolioStructureID: "P030-X10",
            PriorityRank: 2
        },
        ParentTask: null,
        Editor: { Id: 2, Title: "Jane Smith" },
        Portfolio: { Id: 2, Title: "Core Modules", PortfolioStructureID: "PF002" },
        TaskType: { Id: 2, Title: "Enhancement", Level: 1 },
        Author: { Id: 2, Title: "Jane Smith" },
        AssignedTo: [{ Id: 2, Title: "Jane Smith" }],
        ResponsibleTeam: { Id: 2, Title: "Core Team" },
        TaskCategories: [{ Id: 2, Title: "Enhancement" }]
    },
    {
        Id: 3,
        Title: "Replace Old Time Entry Popup with New Time Entry Popup in Task Profile",
        FeedBack: null,
        Comments: null,
        TotalTime: 0,
        PriorityRank: 4.6,
        LocalPriority: 3,
        WorkingAction: null,
        Remark: null,
        EstimatedTimeDescription: "0.00 h",
        TaskID: "T33782",
        Priority: "Medium",
        Status: 5,
        ItemRank: 3,
        IsTodaysTask: false,
        Body: null,
        PercentComplete: 10,
        Categories: null,
        StartDate: "2024-01-13",
        DueDate: null,
        Created: "2024-01-08",
        Modified: "2024-01-18",
        TaskLevel: 1,
        workingThisWeek: false,
        EstimatedTime: 0,
        Project: {
            Id: 30,
            Title: "Task Profile",
            PortfolioStructureID: "P030-X30",
            PriorityRank: 3
        },
        ParentTask: null,
        Editor: { Id: 3, Title: "Mike Johnson" },
        Portfolio: { Id: 2, Title: "Core Modules", PortfolioStructureID: "PF002" },
        TaskType: { Id: 2, Title: "Enhancement", Level: 1 },
        Author: { Id: 3, Title: "Mike Johnson" },
        AssignedTo: [{ Id: 3, Title: "Mike Johnson" }],
        ResponsibleTeam: { Id: 2, Title: "Core Team" },
        TaskCategories: [{ Id: 2, Title: "Enhancement" }]
    },
    {
        Id: 4,
        Title: "Task Management Blueprint & System Architecture Documentation for OMT Mobile App",
        FeedBack: null,
        Comments: null,
        TotalTime: 3,
        PriorityRank: 4.6,
        LocalPriority: 4,
        WorkingAction: null,
        Remark: null,
        EstimatedTimeDescription: "3.00 h",
        TaskID: "T33779",
        Priority: "High",
        Status: 10,
        ItemRank: 4,
        IsTodaysTask: true,
        Body: null,
        PercentComplete: 80,
        Categories: null,
        StartDate: "2024-01-12",
        DueDate: null,
        Created: "2024-01-07",
        Modified: "2024-01-17",
        TaskLevel: 1,
        workingThisWeek: true,
        EstimatedTime: 3,
        Project: {
            Id: 257,
            Title: "OMT Mobile Application",
            PortfolioStructureID: "P257",
            PriorityRank: 1
        },
        ParentTask: null,
        Editor: { Id: 1, Title: "John Doe" },
        Portfolio: { Id: 1, Title: "Mobile Apps", PortfolioStructureID: "PF001" },
        TaskType: { Id: 3, Title: "Documentation", Level: 1 },
        Author: { Id: 1, Title: "John Doe" },
        AssignedTo: [{ Id: 1, Title: "John Doe" }],
        ResponsibleTeam: { Id: 1, Title: "Mobile Team" },
        TaskCategories: [{ Id: 3, Title: "Documentation" }]
    },
    {
        Id: 5,
        Title: "Feedback - deleting empty task",
        FeedBack: "Critical bug reported",
        Comments: null,
        TotalTime: 0.5,
        PriorityRank: 9.8,
        LocalPriority: 5,
        WorkingAction: null,
        Remark: null,
        EstimatedTimeDescription: "0.50 h",
        TaskID: "T33765",
        Priority: "Critical",
        Status: 10,
        ItemRank: 5,
        IsTodaysTask: true,
        Body: null,
        PercentComplete: 5,
        Categories: null,
        StartDate: "2024-01-11",
        DueDate: null,
        Created: "2024-01-06",
        Modified: "2024-01-16",
        TaskLevel: 1,
        workingThisWeek: true,
        EstimatedTime: 0.5,
        Project: {
            Id: 30,
            Title: "Data Validation",
            PortfolioStructureID: "P030-X12",
            PriorityRank: 5
        },
        ParentTask: null,
        Editor: { Id: 4, Title: "Sarah Wilson" },
        Portfolio: { Id: 2, Title: "Core Modules", PortfolioStructureID: "PF002" },
        TaskType: { Id: 4, Title: "Bug Fix", Level: 1 },
        Author: { Id: 4, Title: "Sarah Wilson" },
        AssignedTo: [{ Id: 4, Title: "Sarah Wilson" }],
        ResponsibleTeam: { Id: 2, Title: "Core Team" },
        TaskCategories: [{ Id: 4, Title: "Bug" }]
    },
    {
        Id: 6,
        Title: "POC for Multilingual Functionality Using Resource Files",
        FeedBack: null,
        Comments: null,
        TotalTime: 0,
        PriorityRank: 4.4,
        LocalPriority: 6,
        WorkingAction: null,
        Remark: null,
        EstimatedTimeDescription: "0.00 h",
        TaskID: "T33756",
        Priority: "Medium",
        Status: 5,
        ItemRank: 6,
        IsTodaysTask: false,
        Body: null,
        PercentComplete: 9,
        Categories: null,
        StartDate: "2024-01-10",
        DueDate: null,
        Created: "2024-01-05",
        Modified: "2024-01-15",
        TaskLevel: 1,
        workingThisWeek: false,
        EstimatedTime: 0,
        Project: {
            Id: 256,
            Title: "Multilingual Support",
            PortfolioStructureID: "P256",
            PriorityRank: 6
        },
        ParentTask: null,
        Editor: { Id: 5, Title: "Tom Brown" },
        Portfolio: { Id: 3, Title: "Infrastructure", PortfolioStructureID: "PF003" },
        TaskType: { Id: 5, Title: "POC", Level: 1 },
        Author: { Id: 5, Title: "Tom Brown" },
        AssignedTo: [{ Id: 5, Title: "Tom Brown" }],
        ResponsibleTeam: { Id: 3, Title: "Infrastructure Team" },
        TaskCategories: [{ Id: 5, Title: "Research" }]
    },
    {
        Id: 7,
        Title: "A1333 - P256 - Multilingual Function",
        FeedBack: null,
        Comments: null,
        TotalTime: 0,
        PriorityRank: 4,
        LocalPriority: 7,
        WorkingAction: null,
        Remark: null,
        EstimatedTimeDescription: "0.00 h",
        TaskID: "A1333",
        Priority: "Low",
        Status: 0,
        ItemRank: 7,
        IsTodaysTask: false,
        Body: null,
        PercentComplete: 0,
        Categories: null,
        StartDate: null,
        DueDate: null,
        Created: "2024-01-04",
        Modified: "2024-01-14",
        TaskLevel: 1,
        workingThisWeek: false,
        EstimatedTime: 0,
        Project: {
            Id: 256,
            Title: "Multilingual Support",
            PortfolioStructureID: "P256",
            PriorityRank: 7
        },
        ParentTask: null,
        Editor: { Id: 5, Title: "Tom Brown" },
        Portfolio: { Id: 3, Title: "Infrastructure", PortfolioStructureID: "PF003" },
        TaskType: { Id: 1, Title: "Development", Level: 1 },
        Author: { Id: 5, Title: "Tom Brown" },
        AssignedTo: [{ Id: 5, Title: "Tom Brown" }],
        ResponsibleTeam: { Id: 3, Title: "Infrastructure Team" },
        TaskCategories: [{ Id: 5, Title: "Development" }]
    },
    {
        Id: 8,
        Title: "Implement Public API for Mobile App Using Power Automate",
        FeedBack: null,
        Comments: null,
        TotalTime: 7,
        PriorityRank: 2,
        LocalPriority: 8,
        WorkingAction: null,
        Remark: null,
        EstimatedTimeDescription: "7.00 h",
        TaskID: "T33754",
        Priority: "High",
        Status: 10,
        ItemRank: 8,
        IsTodaysTask: true,
        Body: null,
        PercentComplete: 70,
        Categories: null,
        StartDate: "2024-01-08",
        DueDate: null,
        Created: "2024-01-03",
        Modified: "2024-01-13",
        TaskLevel: 1,
        workingThisWeek: true,
        EstimatedTime: 7,
        Project: {
            Id: 88,
            Title: "Mobile Integration",
            PortfolioStructureID: "P088-X4",
            PriorityRank: 8
        },
        ParentTask: null,
        Editor: { Id: 6, Title: "Lisa Chen" },
        Portfolio: { Id: 1, Title: "Mobile Apps", PortfolioStructureID: "PF001" },
        TaskType: { Id: 1, Title: "Development", Level: 1 },
        Author: { Id: 6, Title: "Lisa Chen" },
        AssignedTo: [{ Id: 6, Title: "Lisa Chen" }],
        ResponsibleTeam: { Id: 1, Title: "Mobile Team" },
        TaskCategories: [{ Id: 1, Title: "Mobile" }]
    },
    {
        Id: 9,
        Title: "POC for OMT Mobile Application",
        FeedBack: null,
        Comments: null,
        TotalTime: 8.5,
        PriorityRank: 4.6,
        LocalPriority: 9,
        WorkingAction: null,
        Remark: null,
        EstimatedTimeDescription: "8.50 h",
        TaskID: "T33752",
        Priority: "High",
        Status: 10,
        ItemRank: 9,
        IsTodaysTask: true,
        Body: null,
        PercentComplete: 75,
        Categories: null,
        StartDate: "2024-01-07",
        DueDate: null,
        Created: "2024-01-02",
        Modified: "2024-01-12",
        TaskLevel: 1,
        workingThisWeek: true,
        EstimatedTime: 8.5,
        Project: {
            Id: 257,
            Title: "OMT Mobile Application",
            PortfolioStructureID: "P257",
            PriorityRank: 1
        },
        ParentTask: null,
        Editor: { Id: 1, Title: "John Doe" },
        Portfolio: { Id: 1, Title: "Mobile Apps", PortfolioStructureID: "PF001" },
        TaskType: { Id: 5, Title: "POC", Level: 1 },
        Author: { Id: 1, Title: "John Doe" },
        AssignedTo: [{ Id: 1, Title: "John Doe" }],
        ResponsibleTeam: { Id: 1, Title: "Mobile Team" },
        TaskCategories: [{ Id: 1, Title: "Mobile" }]
    },
    {
        Id: 10,
        Title: "Integrate Asset Management into SP Site",
        FeedBack: null,
        Comments: null,
        TotalTime: 32.25,
        PriorityRank: 4.4,
        LocalPriority: 10,
        WorkingAction: null,
        Remark: null,
        EstimatedTimeDescription: "32.25 h",
        TaskID: "T33750",
        Priority: "High",
        Status: 10,
        ItemRank: 10,
        IsTodaysTask: true,
        Body: null,
        PercentComplete: 80,
        Categories: null,
        StartDate: "2024-01-06",
        DueDate: null,
        Created: "2024-01-01",
        Modified: "2024-01-11",
        TaskLevel: 1,
        workingThisWeek: true,
        EstimatedTime: 32.25,
        Project: {
            Id: 141,
            Title: "Asset Management",
            PortfolioStructureID: "P141-X3-C1",
            PriorityRank: 10
        },
        ParentTask: null,
        Editor: { Id: 7, Title: "David Lee" },
        Portfolio: { Id: 4, Title: "SharePoint", PortfolioStructureID: "PF004" },
        TaskType: { Id: 1, Title: "Development", Level: 1 },
        Author: { Id: 7, Title: "David Lee" },
        AssignedTo: [{ Id: 7, Title: "David Lee" }],
        ResponsibleTeam: { Id: 4, Title: "SharePoint Team" },
        TaskCategories: [{ Id: 6, Title: "Integration" }]
    },
    {
        Id: 11,
        Title: "Send All Emails via Microsoft Graph API",
        FeedBack: null,
        Comments: null,
        TotalTime: 4,
        PriorityRank: 2,
        LocalPriority: 11,
        WorkingAction: null,
        Remark: null,
        EstimatedTimeDescription: "4.00 h",
        TaskID: "T33737",
        Priority: "Medium",
        Status: 10,
        ItemRank: 11,
        IsTodaysTask: false,
        Body: null,
        PercentComplete: 10,
        Categories: null,
        StartDate: "2024-01-05",
        DueDate: null,
        Created: "2023-12-31",
        Modified: "2024-01-10",
        TaskLevel: 1,
        workingThisWeek: false,
        EstimatedTime: 4,
        Project: {
            Id: 100,
            Title: "Email Integration",
            PortfolioStructureID: "P100",
            PriorityRank: 11
        },
        ParentTask: null,
        Editor: { Id: 8, Title: "Emma Davis" },
        Portfolio: { Id: 3, Title: "Infrastructure", PortfolioStructureID: "PF003" },
        TaskType: { Id: 1, Title: "Development", Level: 1 },
        Author: { Id: 8, Title: "Emma Davis" },
        AssignedTo: [{ Id: 8, Title: "Emma Davis" }],
        ResponsibleTeam: { Id: 3, Title: "Infrastructure Team" },
        TaskCategories: [{ Id: 6, Title: "Integration" }]
    },
    {
        Id: 12,
        Title: "AI Studio Project Deployment on Dogado & Netlify",
        FeedBack: null,
        Comments: null,
        TotalTime: 5,
        PriorityRank: 3.5,
        LocalPriority: 12,
        WorkingAction: null,
        Remark: null,
        EstimatedTimeDescription: "5.00 h",
        TaskID: "T33736",
        Priority: "Medium",
        Status: 10,
        ItemRank: 12,
        IsTodaysTask: false,
        Body: null,
        PercentComplete: 9,
        Categories: null,
        StartDate: "2024-01-04",
        DueDate: null,
        Created: "2023-12-30",
        Modified: "2024-01-09",
        TaskLevel: 1,
        workingThisWeek: false,
        EstimatedTime: 5,
        Project: {
            Id: 200,
            Title: "AI Studio",
            PortfolioStructureID: "P200",
            PriorityRank: 12
        },
        ParentTask: null,
        Editor: { Id: 9, Title: "Alex Kim" },
        Portfolio: { Id: 5, Title: "AI Projects", PortfolioStructureID: "PF005" },
        TaskType: { Id: 6, Title: "Deployment", Level: 1 },
        Author: { Id: 9, Title: "Alex Kim" },
        AssignedTo: [{ Id: 9, Title: "Alex Kim" }],
        ResponsibleTeam: { Id: 5, Title: "AI Team" },
        TaskCategories: [{ Id: 7, Title: "Deployment" }]
    }
];

export const statusFilters = [
    { label: "5%", value: 0.05 },
    { label: "9%", value: 0.09 },
    { label: "10%", value: 0.10 },
    { label: "70%", value: 0.70 },
    { label: "75%", value: 0.75 },
    { label: "80%", value: 0.80 },
    { label: 'All', value: 'All' }
];
